export let myValue1 = 35;
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
export function Utilisateur() {
let nomTag = Tags("@UserName");
let nom = nomTag.Read();
let user = nom.split("_").pop();;

let prefix = Tags("Praefix");
prefix.Write(Number(user));


}
